name: POLAMP_samp_fac_env
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2022.5.18.1=py310h06a4308_0
  - cffi=1.15.0=py310hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=37.0.1=py310h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h2818925_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.22.3=py310hfa59a62_0
  - numpy-base=1.22.3=py310h9585f30_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1o=h7f8727e_0
  - pillow=9.0.1=py310h22f2fdc_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.4=h12debd9_0
  - pytorch=1.11.0=py3.10_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd3eb1b0_0
  - setuptools=61.2.0=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.3=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.11.0=py310_cu113
  - torchvision=0.12.0=py310_cu113
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.9=py310h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.1.0
    - accelerate==0.9.0
    - cachetools==5.2.0
    - cairocffi==1.3.0
    - cairosvg==2.5.2
    - catalyst==22.4
    - click==8.1.3
    - cloudpickle==2.1.0
    - colorlog==6.6.0
    - cssselect2==0.6.0
    - cycler==0.11.0
    - cython==0.29.30
    - decorator==4.4.2
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - drawsvg==1.8.3
    - faster-fifo==1.4.0
    - filelock==3.7.1
    - fonttools==4.33.3
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.7.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.46.3
    - gym==0.24.1
    - gym-notices==0.0.7
    - hydra-slayer==0.4.0
    - imageio==2.19.3
    - imageio-ffmpeg==0.4.7
    - inflection==0.5.1
    - kiwisolver==1.4.2
    - llvmlite==0.38.1
    - markdown==3.3.7
    - matplotlib==3.5.2
    - moviepy==1.0.3
    - numba==0.55.2
    - oauthlib==3.2.0
    - opencv-python==4.6.0.66
    - packaging==21.3
    - pandas==1.4.2
    - pathtools==0.1.2
    - pip==22.1.2
    - pogema==1.0.1
    - proglog==0.1.10
    - promise==2.3
    - protobuf==3.19.4
    - psutil==5.9.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.9.1
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - raylib==4.0.0.6
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - sample-factory==1.121.3
    - scipy==1.8.1
    - sentry-sdk==1.5.12
    - setproctitle==1.2.3
    - shortuuid==1.0.9
    - smmap==5.0.0
    - tabulate==0.8.9
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - tqdm==4.64.0
    - wandb==0.12.17
    - webencodings==0.5.1
    - werkzeug==2.1.2
prefix: /home/reedgern/anaconda3/envs/POLAMP_samp_fac_env
